- name: Start Telegram Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          PUBLIC_HOST: ${{ env.PUBLIC_HOST }}
          WS_PATH: "Télégram/@MOHAMaaaaal/@VLessVMessTroja"
          XRAY_BIN: ${{ env.HOME }}/xray/xray
          XRAY_API: "127.0.0.1:10085"
          CONFIG_PATH: ${{ env.HOME }}/xray/config/config.json
          INBOUND_TAG: "vless-in"
        run: |
          echo "===== XRAY LOG ====="
          cat xray.log

          echo "===== CLOUDFLARE LOG ====="
          cat cloudflared.log

          echo "===== START BOT ====="
          python bot.py